# Generated by Django 5.1.3 on 2025-04-04 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elearnapp", "0006_lecture"),
    ]

    operations = [
        migrations.AddField(
            model_name="lecture",
            name="created_at",
            field=models.DateField(blank=True, null=True),
        ),
    ]
