# Generated by Django 5.1.3 on 2025-04-04 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elearnapp", "0008_notification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lecture",
            name="pdf_file",
            field=models.FileField(blank=True, null=True, upload_to="lectures/pdfs/"),
        ),
        migrations.AlterField(
            model_name="lecture",
            name="video_file",
            field=models.FileField(blank=True, null=True, upload_to="lectures/videos/"),
        ),
    ]
