# Generated by Django 5.1.3 on 2025-04-04 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elearnapp", "0009_alter_lecture_pdf_file_alter_lecture_video_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lecture",
            name="pdf_file",
            field=models.FileField(blank=True, null=True, upload_to="pdfs/"),
        ),
        migrations.AlterField(
            model_name="lecture",
            name="video_file",
            field=models.FileField(blank=True, null=True, upload_to="videos/"),
        ),
    ]
