# Generated by Django 5.1.3 on 2025-04-04 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elearnapp", "0012_question_choice_quiz_question_quiz_studentresponse"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quiz",
            name="time_limit",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
