# Generated by Django 5.1.3 on 2025-04-04 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elearnapp", "0015_question_correct_option_question_option1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="option1",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="question",
            name="option2",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="question",
            name="option3",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="question",
            name="option4",
            field=models.CharField(max_length=255),
        ),
    ]
